### ISSUE TITLE
field sourceurl missing

### ISSUE THREAD

**Issue by andibraeu** [fossasia/timeline.api.fossasia.net#5] opened 2015-07-19 19:59 UTC
@zyzo you introduced ```sourceurl``` with this commit: https://github.com/fossasia/timeline.api.fossasia.net/commit/1139d360c05f83ab72bd1de4644a4052d99a1da3

Now I get error messages, that source url can't be found:
```
Uncaught API error : Field not supported : sourceurl
```

**Comment by zyzo** [comment] 2015-07-20 02:19
@andibraeu where did you get the error message ? If it is the gh-pages, the problem is fixed by merging new changes in master http://fossasia.github.io/timeline.api.fossasia.net/

**Closed** 2015-07-20 02:20 UTC
Labels: bug
